"""add topic_id to FollowUpTask

Revision ID: 54fade981cd3
Revises: 5d4f548e6536
Create Date: 2026-09-10 06:48:52.243428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54fade981cd3'
down_revision: Union[str, Sequence[str], None] = '5d4f548e6536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_follow_up_tasks_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_follow_up_tasks_topic_id'))
        batch_op.drop_column('topic_id')

    # ### end Alembic commands ###
