"""Add Topic and extract decisions

Revision ID: 5d4f548e6536
Revises: db2393f6dc8b
Create Date: 2026-09-09 05:12:33.412607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d4f548e6536'
down_revision: Union[str, Sequence[str], None] = 'db2393f6dc8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topics',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', name='topicstatusenum'), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topics_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('key_message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('evidence_sentence', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_meeting_decisions_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_transcript_segments_topic_id'), ['topic_id'], unique=False)
        batch_op.create_foreign_key(None, 'topics', ['topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transcript_segments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transcript_segments_topic_id'))
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_meeting_decisions_topic_id'))
        batch_op.drop_column('evidence_sentence')
        batch_op.drop_column('key_message')
        batch_op.drop_column('topic_id')

    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topics_meeting_id'))

    op.drop_table('topics')
    # ### end Alembic commands ###
