"""add phase3 tables

Revision ID: a1b2c3d4e5f6
Revises: 762f219efe38
Create Date: 2026-08-03 00:16:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1b2c3d4e5f6'
down_revision: Union[str, None] = '762f219efe38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'tasks',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('workspace_id', sa.String(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.String(), nullable=False),
        sa.Column('assignee_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriorityenum'), nullable=False),
        sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'IN_REVIEW', 'COMPLETED', name='taskstatusenum'), nullable=False),
        sa.Column('due_date', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_workspace_id'), ['workspace_id'], unique=False)

    op.create_table(
        'meeting_invitations',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('role', sa.Enum('ATTENDEE', 'PRESENTER', 'MODERATOR', name='invitationroleenum'), nullable=False),
        sa.Column('token', sa.String(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', name='invitationstatusenum'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_invitations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_invitations_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_invitations_meeting_id'), ['meeting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_meeting_invitations_token'), ['token'], unique=True)

    op.create_table(
        'meeting_files',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('meeting_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by_id', sa.String(), nullable=False),
        sa.Column('filename', sa.String(), nullable=False),
        sa.Column('file_path', sa.String(), nullable=False),
        sa.Column('file_size', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
        sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_files_meeting_id'), ['meeting_id'], unique=False)

    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', name='meetingstatusenum'), server_default='SCHEDULED', nullable=False))
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ended_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('recording_url', sa.String(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table('meetings', schema=None) as batch_op:
        batch_op.drop_column('recording_url')
        batch_op.drop_column('ended_at')
        batch_op.drop_column('started_at')
        batch_op.drop_column('status')

    op.drop_table('meeting_files')
    op.drop_table('meeting_invitations')
    op.drop_table('tasks')
