"""add evidence_quote to follow_up_tasks

Revision ID: a9bbabaa14f7
Revises: 54fade981cd3
Create Date: 2026-09-10 09:07:23.600867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bbabaa14f7'
down_revision: Union[str, Sequence[str], None] = '54fade981cd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('evidence_quote', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.drop_column('evidence_quote')

    # ### end Alembic commands ###
