"""Add issue_id to follow_up_tasks

Revision ID: b72946c793f8
Revises: a9bbabaa14f7
Create Date: 2026-09-11 18:38:01.105944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b72946c793f8'
down_revision: Union[str, Sequence[str], None] = 'a9bbabaa14f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'issues', ['issue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('follow_up_tasks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('issue_id')

    # ### end Alembic commands ###
