"""add_proposer_id_to_meeting_decision

Revision ID: d1d49489330d
Revises: ebaf6242178e
Create Date: 2026-09-01 17:13:17.694682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d49489330d'
down_revision: Union[str, Sequence[str], None] = 'ebaf6242178e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proposer_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['proposer_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('proposer_id')

    # ### end Alembic commands ###
