"""add_meeting_decision

Revision ID: ebaf6242178e
Revises: e5f6a7b8c9d0
Create Date: 2026-08-31 14:22:57.133188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebaf6242178e'
down_revision: Union[str, Sequence[str], None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_decisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('transcript_segment_id', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'AGREED', 'REJECTED', name='meetingdecisionstatusenum'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['transcript_segment_id'], ['transcript_segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_meeting_decisions_meeting_id'), ['meeting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meeting_decisions_meeting_id'))

    op.drop_table('meeting_decisions')
    # ### end Alembic commands ###
